modLoader="neoforge"
loaderVersion="[1.21.1,)"

license="MIT"
modId="neoforge_mod"

version="${file.jarVersion}"
displayName="NeoForge Example Mod"
credits="DinoNuggies9611"
authors="GitHub Starter Template"

description='''
A template for NeoForge 1.21.1 mods with creative tabs, advancements, JEI/REI hooks.
'''
